languagename = "ğŸŒ \u00a0\u00a0 ğŸ‡ºğŸ‡¸/ğŸ‡¬ğŸ‡§"
title = "Leo Carvalho"

[params]
info = "Back-end developer, development teacher, and Ph.D. in bad jokes"
description = "Leo Carvalho is a back-end developer (Node.js) and development teacher. Christian, 26y, graduated in Systems' Analysis and Development on EstÃ¡cio and single until now."
keywords = "leo carvalho, node developer, node.js developer, node, node.js, javascript, back-end developer, expressjs, git, github, technical blog, tech blog, tutorial, blog, leo carvalho dev, leo carvalho developer"

[menu]

[[menu.main]]
  name = "About me"
  weight = 1.0
  url = "/about/"

[[menu.main]]
    name = "Legal"
    weight = 1.5
    url = "/terms/"