languagename = "Portuguese"
title = "Léo Carvalho"

[params]
    description = "Léo Carvalho é desenvolvedor back-end (Node.js, PHP e C#) e professor de programação. Cristão, tem 25 anos, é graduado em Análise e Desenvolvimento de sistemas pela Estácio e solteiro até agora."
    keywords = "léo carvalho, desenvolvedor c#, desenvolvedor node, desenvolvedor node.js, desenvolvedor php, .net, c#, node, node.js, javascript, desenvolvedor back-end, expressjs, git, github, blog técnico, tutorais, blog"
    info = "Desenvolvedor back-end, professor de programação e falador de abobrinha"

[menu]
    [[menu.main]]
    name = "Sobre mim"
    weight = 1.0
    url = "/about/"

    [[menu.main]]
    name = "Blog"
    weight = 2.0
    url = "/posts/"